# config/_default/params.toml

colorScheme = "slate"

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true
enableQuicklink = true

robots = "noarchive"

[header]
  layout = "hybrid"

[homepage]
  layout = "profile"
  showRecent = false

[article]
  showEdit = true
  showDateUpdated = true
  editURL = "https://github.com/mariomenjr/mariomenjr/edit/main/content"
  showTableOfContents = true
  showBreadcrumbs = true
  sharingLinks = ["facebook", "twitter", "mastodon", "reddit", "linkedin"]

[list]
  showBreadcrumbs = true
  showSummary = false
  showTableOfContents = true
  showTaxonomies = false
  groupByYear = false
  paginationWidth = 1

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[footer]
  showAppearanceSwitcher = true

[verification]
  google="NspysIBon3Yhy_TQbJtYWM7ffCfRAC2ncngp4s8-hLI"